/**
 * Scratchpad types for storing alternative segment recommendations
 * @module domain/types/scratchpad
 */

import type { ItineraryId, SegmentId } from './branded.js';
import type { Segment } from './segment.js';
import { SegmentType } from './common.js';

/**
 * Source of a scratchpad item
 * - designer: Generated by Trip Designer AI
 * - agent: Generated by Travel Agent AI
 * - user: Manually added by user
 * - search: Found via search/discovery
 */
export type ScratchpadSource = 'designer' | 'agent' | 'user' | 'search';

/**
 * Priority level for scratchpad items
 */
export type ScratchpadPriority = 'high' | 'medium' | 'low';

/**
 * Branded type for Scratchpad Item IDs
 */
export type ScratchpadItemId = string & { readonly __brand: 'ScratchpadItemId' };

/**
 * A single item in the scratchpad - an alternative segment recommendation
 */
export interface ScratchpadItem {
  /** Unique item identifier */
  id: ScratchpadItemId;
  /** Parent itinerary ID */
  itineraryId: ItineraryId;
  /** The segment data (reuses existing Segment type) */
  segment: Segment;
  /** Timestamp when item was added */
  addedAt: Date;
  /** Source of the recommendation */
  source: ScratchpadSource;
  /** Optional notes explaining why this was recommended */
  notes?: string;
  /** Priority level for this alternative */
  priority?: ScratchpadPriority;
  /** Tags for filtering and organization */
  tags: string[];
  /** Related segment ID that this could replace (optional) */
  relatedSegmentId?: SegmentId;
}

/**
 * Organized scratchpad for an itinerary
 * Stores alternative recommendations by type for easy access
 */
export interface Scratchpad {
  /** Parent itinerary ID */
  itineraryId: ItineraryId;
  /** All scratchpad items (flat list) */
  items: ScratchpadItem[];
  /** Items organized by segment type for quick filtering */
  byType: ScratchpadByType;
}

/**
 * Scratchpad items organized by segment type
 */
export interface ScratchpadByType {
  [SegmentType.FLIGHT]: ScratchpadItem[];
  [SegmentType.HOTEL]: ScratchpadItem[];
  [SegmentType.ACTIVITY]: ScratchpadItem[];
  [SegmentType.TRANSFER]: ScratchpadItem[];
  [SegmentType.MEETING]: ScratchpadItem[];
  [SegmentType.CUSTOM]: ScratchpadItem[];
}

/**
 * Result of swapping a scratchpad item with an existing segment
 */
export interface SwapResult {
  /** The segment that was removed from the itinerary */
  removedSegment: Segment;
  /** The segment that was added to the itinerary (from scratchpad) */
  addedSegment: Segment;
  /** The scratchpad item that was used */
  scratchpadItem: ScratchpadItem;
}
